### ISSUE TITLE
Error while adding implementation of version 1.1.0

### ISSUE THREAD

**Issue by AlanMejia10** [SmartToolFactory/Compose-RatingBar#1]
I tried to use the lastest version 1.1.0, but it's showing me this message
Failed to resolve: com.github.SmartToolFactory:Compose-RatingBar:1.1.0

**Comment by SmartToolFactory** [comment]
Let me check jitpack.io. This is because of build error i guess. I will migrate libraries to maven soon.

**Comment by AlanMejia10** [comment]
Thank you 🦖

**Comment by SmartToolFactory** [comment]
Updated jitpack version to 1.1.1. Now it builds. I will migrate all of my libraries to maven soon. Thanks for letting me know.
